
using Dalamud.Interface;

namespace Sundouleia.DrawSystem;

/// <summary>
///     Public accessor for a node inside a DynamicDrawSystem.
/// </summary>
public interface IDynamicNode
{
    /// <summary>
    ///     Unique ID for a node in the DynamicDrawSystem.
    /// </summary>
    public uint ID { get; }

    /// <summary>
    ///     The Label associated with this node.
    /// </summary>
    public string Name { get; }

    /// <summary>
    ///     Path used by the DynamicDrawSystem for lookup and creation. <para />
    ///     Paths are generated by the hierarchy of node names. <para />
    ///     <b>FolderCollections</b> split paths with '//', while <b>Folders</b> use '/'.
    /// </summary>
    public string FullPath { get; }

    // Depth was here, we can insert it if necessary for line indentations.

    /// <summary>
    ///     If this folder is the root folder. (Root has ID 0)
    /// </summary>
    public bool IsRoot { get; }

    /// <summary>
    ///     Retrieve all ancestors of this node, excluding root.
    /// </summary>
    public IReadOnlyList<IDynamicFolderNode> GetAncestors();
}